### ISSUE TITLE
Lambda function to relay Bitcoin block header

### ISSUE THREAD

**Issue by Clearwood** [strudel-finance/monorepo#55]
## Spec

Execute the following in an interval: 

1. Call getBestKnownDigest on [Relayer Contract](https://etherscan.io/address/0x1531b6e3d51bf80f634957df81a990b92da4b154)
2. Get blockHeight of getBestKnownDigest
3. Check for latest BlockHeight using public SoChain API
4. If BlockHeight is larger than getBestKnownDigest check for inclusion of following blocks on relay contract using findHeight(txHash in Little Endian https://github.com/strudel-finance/monorepo/blob/a6d48c001acb40cdc64d8bc046cd6878c82388eb/packages/frontend/src/utils/changeEndian.ts#L1-L6)
5. If Block is not included call getBlockHeader(txHash in bigEndian) in hex on our Bitcoin RPC server
6. Combine blockHeaders into parameter string
7. get BlockHeader in hex for bestKnownDigest
8. Call [ReserveController](https://etherscan.io/address/0xe1406825186d63980fd6e2ec61888f7b91c4bae4) with addHeader function setting blockHeader of bestKnownDigest as _anchor and fetched succeeding block headers as _headers
9. After Confirmation call markNewHeaviest on [Relayer Contract](https://etherscan.io/address/0x1531b6e3d51bf80f634957df81a990b92da4b154) with getBestKnownDigestancestor (in LE as ancestor, blockhash of getBestKnownDigest for currentBest and blockHeader of last included block as _newBest, _limit at 200

**Comment by johannbarbie** [comment]
will use tBTC's relayer.
