### ISSUE TITLE
problem with ethTxHash

### ISSUE THREAD

**Issue by Clearwood** [strudel-finance/monorepo#56]
Problem with ethTxHash, how is the situation in database.
![2020-10-11-16-29-strudel finance](https://user-images.githubusercontent.com/11144110/95680072-29acd980-0bd7-11eb-8437-61146a38e76f.png)

**Comment by mwaa** [comment]
Can't deposit to any of the farms.

**Comment by johannbarbie** [comment]
hopefully fixed
