### ISSUE TITLE
Blank page with error is shown when disconnecting MetaMask

### ISSUE THREAD

**Issue by eshavkun** [strudel-finance/monorepo#61]
Reproduction:

1. Go to strudel.finance
2. Click Unlock Wallet and use MetaMask to connect account
3. In MetaMask disconnect account (click on "Connected" in top left corner, open menu and select "Disconnect")

Page is reloaded and becomes blank with following error:
```
Something went wrong:

t is null
```

**Comment by MaxKuck** [comment]
![Uploading image.png…]()
