### ISSUE TITLE
[UX] vBTC-ETH Pool deposit - Allow user to input amount of ETH/vBTC to deposit

### ISSUE THREAD

**Issue by eshavkun** [strudel-finance/monorepo#63]
Currently user can only input the amount of vBTC++ they want to receive and the page will show how much vBTC and ETH they need. But there is no way to know how much vBTC++ they will get given the amount of of ETH and vBTC they want to supply. To improve this, ETH and vBTC fields should be editable as well as vBTC++ field (with respective calculations on input)

**Comment by johannbarbie** [comment]
outdated
