### ISSUE TITLE
Rewards for Tweets and Post in Frequented TG Groups

### ISSUE THREAD

**Issue by Clearwood** [strudel-finance/monorepo#66]
I would like to put up Strudel rewards for tweets mentioning us (maybe like 2 $TRDL each for unique accounts with more than 200 followers) and new messages into telegram groups or Forums with more than 1k people. Group needs to be unique, double post or tweets not being rewarded.
Reward request would need to be managed through a Google form and paid out quickly.

**Comment by johannbarbie** [comment]
difficult / teadious
