### ISSUE TITLE
Problems with responsiveness on unusual screen configurations

### ISSUE THREAD

**Issue by Clearwood** [strudel-finance/monorepo#86]
The new updates with manageing inactive pool means that they are displayed in a widened row, this is non conforming with our current break points and therefore is displayed only partly on some unusual combinations like the iPad. 
![image](https://user-images.githubusercontent.com/11144110/96334937-be4e8600-1074-11eb-894e-d610f1240900.png)

**Comment by johannbarbie** [comment]
pool have been removed. fine now
